<?php

namespace AppBundle\Repository;

/**
 * BatteryJournalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatteryJournalRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAggregatedData()
    {


        // createQueryBuilder automatically selects FROM AppBundle:Product
        // and aliases it to "p"
        $query = $this->createQueryBuilder('p')
            ->addSelect('p.type')
            ->addSelect('sum(p.amount) as amount')
            ->groupBy('p.type')
            ->getQuery();

        return $query->getResult();


    }
}
